### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### odoo-brazil/odoo-brazil-eletronic-documents now has a Chat Room on Gitter

@mileo has just created a chat room. You can visit it here: [https://gitter.im/odoo-brazil/odoo-brazil-eletronic-documents](https://gitter.im/odoo-brazil/odoo-brazil-eletronic-documents?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/odoo-brazil/odoo-brazil-eletronic-documents?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by danimaribeiro** [comment]
Tem como criar uma só para o odoo-brazil ?

**Comment by mileo** [comment]
https://gitter.im/odoo-brazil/odoo-brazil?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by mileo** [comment]
[Gitter]https://gitter.im/odoo-brazil/odoo-brazil?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

**Comment by mileo** [comment]
This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/odoo-brazil/odoo-brazil?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

**Comment by mileo** [comment]
Agora foi

**Comment by danimaribeiro** [comment]
:+1:

**Pull request closed without merging**
